### ISSUE TITLE
code?

### ISSUE THREAD

**Issue by Utopiah** [cognitiveailab/neurosymbolic#1]

**Comment by PeterAJansen** [comment]
Thanks -- we submitted the camera ready for EACL on Friday, so moving over the code to this repository and writing some documentation is on my TODO list for this week.  If you can't wait and want access to the development repository, just let me  know.

**Comment by Utopiah** [comment]
I can wait, thanks for the update, please close this issue once done so that I get a notification and try. Thanks for the interesting work!

**Comment by PeterAJansen** [comment]
Thanks -- I think we have the repository up, with a solid set of documentation.  Just let me know if you run into any issues!
