### ISSUE TITLE
mapreader-random needs to be added to the main branch in textworldexpress

### ISSUE THREAD

**Issue by PeterAJansen** [cognitiveailab/neurosymbolic#2]
^^

**Comment by MarcCote** [comment]
We will actually use `mapreader` to refer to the version with random locations. So, this repo should use `mapreader` instead of `mapreader-random`.

**Comment by MarcCote** [comment]
Done in https://github.com/cognitiveailab/TextWorldExpress/commit/e1afc5cecd9490e476692a57cda68e20b0403270
